### ISSUE TITLE
“指针移动时会自动黏附各种按钮、超链接” 这个是只针对浏览器生效的吗？

### ISSUE THREAD

**Issue by photkey** [snomiao/capslockx#2]
如题，这个是只针对浏览器有效，还是全局生效，所有软件界面都支持？

**Comment by snomiao** [comment]
全局，所有软件都支持（各种游戏内应该无效）

原理是指针形状变化时自动减速。

（但一般软件的按钮不对指针形状进行改变，这种按钮就黏附不了）

**Comment by snomiao** [comment]
对了，这个仓库是我的个人同步仓库，以后的 issue 建议发到 [主仓库](https://github.com/snolab/CapsLockX/issues)
